use oee;
WITH RollingAvg AS (
    SELECT EQUIPMENTNAME, DATETIME, OUTPUTCOUNT,
           AVG(OUTPUTCOUNT) OVER (PARTITION BY EQUIPMENTNAME ORDER BY DATETIME ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS rolling_avg_1d
    FROM prepoc_amountchange
)
SELECT * FROM RollingAvg;
